sudo: required

services:
  - docker

language: node_js
node_js:
  - "0.12"
  - 4.4.7
  - 5.10.1
  - 6.3.0

before_install:
  - echo 'DOCKER_OPTS="-s devicemapper --storage-opt dm.basesize=30G"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - START=$(date +%s);
  - sudo docker pull tchughesiv/cf-mini
  - END=$(date +%s);
  - echo $((END-START)) | awk '{print int($1/60)":"int($1%60)}'
  - sudo docker run --privileged -v /lib/modules:/lib/modules:ro -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini
  - sudo apt-get update
  - sudo apt-get install dnsmasq
  - sudo docker ps
  - IMAGE=`sudo docker ps | grep tchughesiv/cf-mini | awk '{print $1}'`
  - sudo docker inspect $IMAGE
  - sudo docker logs $IMAGE
  - IP=`sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${IMAGE}`
  - echo "address=/cf-mini.example/${IP}" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - sudo dpkg-reconfigure resolvconf
  - sudo /etc/init.d/dnsmasq restart
  - ping -c 4 api.cf-mini.example
  - START=$(date +%s);
  - until $(curl --output /dev/null --silent --head --fail http://myhost:myport); sleep 5; done
  - END=$(date +%s);
  - echo $((END-START)) | awk '{print int($1/60)":"int($1%60)}'
  - curl http://hello.cf-mini.example

install: npm i

script: npm run lint
