sudo: required

env:
  global:
    - LOCAL_INSTANCE_1_CF_API_URL=https://api.cf-mini.example
    - LOCAL_INSTANCE_1_username=admin
    - LOCAL_INSTANCE_1_password=c1oudc0w
services:
  - docker

language: node_js
node_js:
  - 4.4.7
  - 5.10.1
  - 6.3.0

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libdevmapper* libudev* udev aufs-tools libdevmapper-event* libudev-dev libdevmapper-dev golang make gcc btrfs-tools libsqlite3-dev overlayroot debootstrap linux-image-generic linux-image-extra-$(uname -r) curl apt-transport-https ca-certificates
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo touch /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get purge lxc-docker
  - sudo apt-cache policy docker-engine
  - sudo apt-get -y install docker-engine
  - echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - echo 'DOCKER_OPTS="-s devicemapper --storage-opt dm.basesize=30G"' | sudo tee /etc/default/docker > /dev/null
  - echo 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' | sudo tee /etc/default/grub > /dev/null
  - sudo update-grub
  - sudo service docker restart
  - sleep 5
  - docker version
  - START=$(date +%s);
  - sudo docker pull tchughesiv/cf-mini
  - END=$(date +%s);
  - echo $((END-START)) | awk '{print int($1/60)":"int($1%60)}'
  - sudo docker run --privileged -d -v /lib/modules:/lib/modules:ro -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini
  - sudo apt-get update
  - sudo apt-get install dnsmasq httping
  - sudo docker ps
  - IMAGE=`sudo docker ps | grep tchughesiv/cf-mini | awk '{print $1}'`
  - IP=`sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${IMAGE}`
  - echo "address=/cf-mini.example/${IP}" | sudo tee -a /etc/dnsmasq.conf > /dev/null
  - sudo dpkg-reconfigure resolvconf
  - sudo /etc/init.d/dnsmasq restart
  - ping -c 4 api.cf-mini.example

install: npm i

script:
  - npm run lint
  - IMAGE=`sudo docker ps | grep tchughesiv/cf-mini | awk '{print $1}'`
  - START=$(date +%s);
  - until  $(curl --output /dev/null --silent --head --fail http://hello.cf-mini.example) ; do sleep 35;sudo docker logs $IMAGE ; done
  - END=$(date +%s);
  - echo $((END-START)) | awk '{print int($1/60)":"int($1%60)}'
  - START=$(date +%s);
  - until  $(curl --output /dev/null --silent --head --fail http://hello.cf-mini.example) ; do sleep 35;sudo docker logs $IMAGE ; done
  - END=$(date +%s);
  - echo $((END-START)) | awk '{print int($1/60)":"int($1%60)}'
  - echo "sleeping for 5 minutes to wait for CF to start"
  - sleep 500
  - sudo docker logs $IMAGE
  - npm run test:local
