environment:
  nodejs_version: "5.10.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run lint

# Don't actually build.
build: off
